print("Content_type: text/html\r\n")
print("\r\n")

print("<!DOCTYPE html>")
print("<html>")
print("")
print("<head>")
print("    <title>Document</title>")
print("</head>")
print("")
print("<body>")
print("    <video src='video2.mp4' width='640' height='360' controls>")
print("        Your browser does not support the video tag.")
print("    </video>")
print("")
print("</body>")
print("")
print("</html>")
