print("<!DOCTYPE html>")
print("<html lang='en>")
print("")
print("<head>")
print("    <meta charset='UTF-8'>")
print("    <meta http-equiv='X-UA-Compatible' content='IE=edge'>")
print("    <meta name='viewport' content='width=device-width, initial-scale=1'>")
print("    <title>ebouabba</title>")
print("    <link rel='stylesheet' href='style.py'>")
print("    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script|Poppins&display=swap' rel='stylesheet'>")
print("</head>")
print("")
print("<body>")
print("    <section id='banner'>")
print("        <!-- <img src='image/ebb.png' class='log'> -->")
print("        <div class='nom'>")
print("            <h1>About Me</h1>")
print("            <p>My name is <b>Mehdi</b>. I am a software engineer. <br>")
print("                I am 23 years old and live in Oued zem.</p>")
print("            <div class='pagge'>")
print("")
print("                <a target='_blank' href='https://www.facebook.com/ebouabba/'><span></span>Facebook</a>")
print("                <a target='_blank' href='https://github.com/ebouabba'><span></span>Github</a>")
print("                <a target='_blank'")
print("                    href='https://www.linkedin.com/in/el-mehdi-bouabbadi-82227a233/'><span></span>Linkedin</a>")
print("                <a target='_blank' href='https://www.instagram.com/ebouabba/'><span></span>Instagram</a>")
print("")
print("")
print("")
print("            </div>")
print("        </div>")
print("    </section>")
print("    <div id='info'>")
print("        <nav>")
print("            <ul>")
print("                <li><a >HOME</a></li>")
print("                <li><a >PROFILE</a></li>")
print("                <li><a >HELP</a></li>")
print("                <li><a >CHAT</a></li>")
print("            </ul>")
print("        </nav>")
print("    </div>")
print("    <div id='info_a'>")
print("        <img src='image/open.png' id='menu'>")
print("    </div>")
print("    <script>")
print("        var info_a = document.getElementById('info_a')")
print("        var info = document.getElementById('info')")
print("        var menu = document.getElementById('menu')")
print("")
print("        info_a.onclick = function () {")
print("            if (info.style.right == '-150px') {")
print("                info.style.right = '0';")
print("                menu.src = 'image/close.png'")
print("            }")
print("            else {")
print("                info.style.right = '-150px';")
print("                menu.src = 'image/open.png'")
print("            }")
print("        }")
print("    </script>")
print("</body>")
print("")
print("</html>")