print("* {")
print("    margin: 0;")
print("    padding: 0;")
print("    font-family: 'Poppins', 'sans-serif';")
print("}")
print("")
print("#banner {")
print("    background: linear-gradient(rgba(41, 85, 206, 0.6), #000000), url(image/back.jpg);")
print("    background-size: cover;")
print("    background-position: center;")
print("    height: 100vh;")
print("}")
print("")
print("/* .logo {")
print("    height: 120px;")
print("    width: 120px;")
print("    position: absolute;")
print("    left: 5%;")
print("    top: 5%;")
print("} */")
print("")
print(".nom {")
print("    text-align: center;")
print("    padding-top: 180px;")
print("    color: rgb(255, 255, 255);")
print("}")
print("")
print(".nom h1 {")
print("    font-size: 90px;")
print("    font-style: italic;")
print("    font-family: 'Kaushan Script', cursive;")
print("}")
print("")
print(".nom p {")
print("    font-size: 30px;")
print("    font-style: italic;")
print("}")
print("")
print(".pagge {")
print("    margin: 70px auto 0;")
print("}")
print("")
print("")
print(".pagge a {")
print("    width: 150px;")
print("    text-decoration: none;")
print("    display: inline-block;")
print("    margin: 0 10px;")
print("    padding: 12px 0;")
print("    color: rgb(255, 255, 255);")
print("    border: .5px solid rgb(255, 255, 255);")
print("    position: relative;")
print("    z-index: 1;")
print("    transition: color 0.5s;")
print("}")
print("")
print(".pagge a span {")
print("    width: 0%;")
print("    height: 100%;")
print("    position: absolute;")
print("    top: 0;")
print("    left: 0;")
print("    background: #fff;")
print("    z-index: -1;")
print("    transition: 0.5s;")
print("}")
print("")
print(".pagge a:hover span {")
print("    width: 100%;")
print("}")
print("")
print(".pagge a:hover {")
print("    color: #000000;")
print("}")
print("")
print("#info {")
print("    height: 100vh;")
print("    width: 150px;")
print("    /* background: rgba(101, 132, 218, 0.5); */")
print("    position: fixed;")
print("    right: -150px;")
print("    top: 0;")
print("    z-index: 2;")
print("    transition: 0.5s;")
print("}")
print("")
print("nav ul li {")
print("    list-style: none;")
print("    display: inline-block;")
print("    margin: 20px;")
print("}")
print("")
print("nav ul li a {")
print("    width: 60px;")
print("    text-decoration: none;")
print("    display: inline-block;")
print("    margin: 0 1px;")
print("    padding: 1px 0;")
print("    color: rgb(247, 247, 247);")
print("    border: 2px solid rgb(0, 0, 0);")
print("    position: relative;")
print("    z-index: 1;")
print("    transition: color 0.5s;")
print("}")
print("")
print("#info_a {")
print("    height: 50px;")
print("    width: 50px;")
print("    position: fixed;")
print("    text-align: center;")
print("    right: 20px;")
print("    top: 15px;")
print("    border-radius: 3px;")
print("    z-index: 6;")
print("    cursor: pointer;")
print("}")
print("")
print("#info_a img {")
print("    width: 30px;")
print("    margin-top: 0px;")
print("}")
print("")
print("@media screen and (max-width:770px) {")
print("    .nom h1 {")
print("        font-size: 44px;")
print("    }")
print("    .nom p {")
print("        margin: 20px auto;")
print("        display: block;")
print("    }")
print("    ")
print("}")